[package]
name = "ironclad-shell"
version = "0.1.0"
edition = "2021"
authors = ["leonardo-kazu <lkazu@duck.com>"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
libc = "0.2.142"
regex = "1.8.1"
